### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Mortycio** [mortuusars/Horseman#2]
The mod doesn't work for me. When used together with the 'Cull Less Leaves' and 'More Culling' mods, the game crashes and the resulting report identifies the error as an incompatibility between the two aforementioned mods.

https://mclo.gs/nywLW97

However, if I disable one of these two mods, the game still crashes with code 1, but without any detected error.

https://mclo.gs/O9eNSsX

mod version: 1.0.2
minecraft version: 1.20.1
fabric loader: 0.16.0
java version: 17.0.12

**Comment by mortuusars** [comment]
Fixed in 1.1.1.
